# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harold Treen
email: haroldtreen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just another nerd.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://haroldtreen.com" # the base hostname & protocol for your site
twitter_username: haroldtreen
github_username:  haroldtreen

include: ['js/', 'show-code/build/']

# Build settings
markdown: kramdown
permalink: pretty
